### ISSUE TITLE
Handle \breve

### ISSUE THREAD

**Issue by siddalp-actual** [siddalp-actual/lilypondEventsProcessing#5]
When a .ly file contains notes of length \breve, the notes file contains further instructions:
```
3.50000000      note    67      log = -1        2.00000000      4       0.75000000      col-and-line 4 57
```
Which leads to:
```
~/github/lilypondEventsProcessing/notes2midi.py
Traceback (most recent call last):
  File "/home/siddalp/github/lilypondEventsProcessing/notes2midi.py", line 112, in <module>
    music = lilyNotes.score.Score(work_files)
  File "/home/siddalp/github/lilypondEventsProcessing/lilyNotes/score.py", line 52, in __init__
    self.lily_staff[staff] = lilyNotes.staff.Staff(
  File "/home/siddalp/github/lilypondEventsProcessing/lilyNotes/staff.py", line 38, in __init__
    self.process(line)
  File "/home/siddalp/github/lilypondEventsProcessing/lilyNotes/staff.py", line 46, in process
    self.process_event(fields)
  File "/home/siddalp/github/lilypondEventsProcessing/lilyNotes/staff.py", line 64, in process_event
    {
  File "/home/siddalp/github/lilypondEventsProcessing/lilyNotes/staff.py", line 296, in process_note
    clicks=int(float(note_duration) * 4 * Staff.CLICKS_PER_BEAT),
ValueError: could not convert string to float: '='
```

**Comment by siddalp-actual** [comment]
in a note event, following the midi pitch, we normally see:
 - the lilypond note length, eg 4 for quarter note, 2. for dotted minim etc
 - the note duration in whole notes, eg 0.25 for quarter note, 0.75 for dotted minim
 
it looks like this idea has been continued for a breve: one could imagine that if a quarter note has lilypond representation 4, minim 2, and semi-breve (whole note) 1, then a breve must have value 1/2, or 2**-1 and in this context 'log = -1' almost 
makes sense.

So, all I've got to do, is recognize this special sequence and translate accordingly.
